#!/bin/bash
clear
APP_SID=$(grep APP_SID .env | cut -d '=' -f2)
APP_SRC=$(grep APP_SRC .env | cut -d '=' -f2)
APP_PORT=$(grep APP_PORT .env | cut -d '=' -f2)
PHP_V=$(grep PHP_V .env | cut -d '=' -f2)
DB_NAME=$(grep DB_NAME .env | cut -d '=' -f2)
DB_PASS=$(grep DB_PASS .env | cut -d '=' -f2)
DB_PORT=$(grep DB_PORT .env | cut -d '=' -f2)
DB_VERS=$(grep DB_VERS .env | cut -d '=' -f2)
PMA_PORT=$(grep PMA_PORT .env | cut -d '=' -f2)
MH_PORT=$(grep MH_PORT .env | cut -d '=' -f2)
echo "\n"
echo "******************************************************"
echo "                           _            _      __   "
echo "   ___  __ _ ___ _   _  __| | ___   ___| | __  \ \  "
echo "  / _ \/ _' / __| | | |/ _' |/ _ \ / __| |/ / (_) | "
echo " |  __/ (_| \__ \ |_| | (_| | (_) | (__|   <   _| | "
echo "  \___|\__,_|___/\__, |\__,_|\___/ \___|_|\_\ ( ) | "
echo "                 |___/                        |/_/  "
echo ""
echo "****************************************************** \n"
echo "\033[1mAPPLICATION\033[0m"
echo "NAME: $APP_SID"
echo "PATH: $APP_SRC"
if [ $APP_PORT == "80" ]
then
   echo "HOST: http://localhost"
else
   echo "HOST: http://localhost:$APP_PORT"
fi
if [ $DB_VERS == "5" ]
then
   echo "VERS: php:$PHP_V / mysql:5.7 \n"
else
   echo "VERS: php:$PHP_V / mysql:8 \n"
fi
echo "\033[1mMYSQL\033[0m"
echo "HOST: mysql:3306 (int) / 127.0.0.1:$DB_PORT (ext)"
echo "NAME: $DB_NAME"
echo "USER: root"
echo "PASS: $DB_PASS \n"
echo "\033[1mSMTP\033[0m"
echo "HOST: mailhog"
echo "PORT: 1025"
echo "USER: "
echo "PASS:  \n"
echo "\033[1mSERVICE\033[0m"
echo "phpmyadmin                 http://localhost:$PMA_PORT"
echo "Mail Hog                   http://localhost:$MH_PORT \n"
echo "\033[1mSCRIPTS\033[0m"
echo "Start:                     sh ed-start"
echo "Stop:                      sh ed-stop"
echo "SSH:                       sh ed-conn \n"
echo "\033[1mOTHER SCRIPTS\033[0m"
echo "Rebuild .env config:       sh ed-build"
echo "Permissions fix:           sh ed-owner"
echo "Reset app:                 sh ed-reset"
echo "1st time init:             sh ed-init \n"
echo "****************************************************** \n"