#!/bin/bash
clear
FILE=./.env
if test -f "$FILE"; then
    echo "easydock was already init ;) \n"
else
    echo "Welcome in easydock ;) \n"
    sleep 1s
    chmod -R 775 easydock
    chmod -R 775 application
    echo "Wait... \n"
    sleep 1s
    cp .env.example .env
    docker-compose build --no-cache --pull
    clear
    echo "easydock is ready! ;) \n"
fi
