#!/bin/bash
clear
    read -r -p "Are you shure to stop easydock? (Y/n): " -n 1 -r
if [[ $REPLY =~ ^[Yy]$ ]]
then
    clear
    echo "Wait... \n"
    docker-compose down
    clear
    echo "easydock has been stopped ;) \n"
fi