#!/bin/bash
clear
FILE=./.env
APP_PORT=$(grep APP_PORT .env | cut -d '=' -f2)
PMA_PORT=$(grep PMA_PORT .env | cut -d '=' -f2)
MH_PORT=$(grep MH_PORT .env | cut -d '=' -f2)
if test -f "$FILE"; then
    echo "Wait... \n"
    docker-compose up -d --force-recreate
    clear
    if [ $APP_PORT == "80" ]
    then
    echo "easydock has been started... visit http://localhost ;) \n"
    else
    echo "easydock has been started... visit http://localhost:$APP_PORT ;) \n"
    fi
else
    echo "easydock .env file not found. Run 'sh ed-init' ;) \n"
fi