version: '3'
services:

  # Application
  app:
    build:
      context: .
      dockerfile: ${APP_DIR}/.easydock/Dockerfile
      args:
        - PHP_VERSION=${PHP_VERSION}
        - APP_WORKER=${APP_WORKER}
    container_name: ${APP_SID}-app
    restart: always
    tty: true
    environment:
      SERVICE_NAME: app
    working_dir: /var/www
    volumes:
      - ${APP_DIR}/:/var/www/:cached
      - ${APP_DIR}/.easydock/config/php/php.ini:/usr/local/etc/php/conf.d/local.ini
      - ${APP_DIR}/.easydock/config/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini

  # Nginx
  nginx:
    image: nginx:alpine
    container_name: ${APP_SID}-nginx
    restart: always
    tty: true
    ports:
      - ${APP_PORT}:80
    volumes:
      - ${APP_DIR}/:/var/www/
      - ${APP_DIR}/.easydock/config/nginx/:/etc/nginx/conf.d/

  # MySQL (MariaDB)
  mysql:
    #image: mariadb:latest
    image: yobasystems/alpine-mariadb:latest
    container_name: ${APP_SID}-mysql
    restart: always
    tty: true
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci','--default-authentication-plugin=mysql_native_password']
    volumes:
      - ${APP_DIR}/.easydock/data:/var/lib/mysql/

  # Redis
  redis:
    image: redis:latest
    container_name: ${APP_SID}-redis
    restart: always
    expose:
      - 6379
    ports:
      - ${RDS_PORT}:6379

  # PHPMyAdmin
  #phpmyadmin:
  #  image: phpmyadmin/phpmyadmin:latest
  #  container_name: ${APP_SID}-pma
  #  restart: always
  #  environment:
  #    PMA_HOST: mysql
  #    MYSQL_ROOT_PASSWORD: ${DB_PASS}
  #  ports:
  #    - ${PMA_PORT}:80

  # Adminer (PHPMyAdmin Alternative)
  adminer:
    image: adminer:latest
    container_name: ${APP_SID}-adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mysql
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - ${PMA_PORT}:8080

  # MailHog
  mailhog:
    image: mailhog/mailhog:latest
    container_name: ${APP_SID}-mailhog
    restart: always
    expose:
      - 1025
    ports:
      - ${MH_PORT}:8025