name: easydock-linux
on:
  push:
    branches:
      - linux
      - master
  pull_request:
    branches: 
      - master
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v5
      # Runs composer install Laravel for testing
      - name: Composer install Laravel
        run: composer create-project laravel/laravel test-app
      # Prepare Laravel sample application
      #- name: Prepare Laravel Application
      #  run: |
      #    cd test-app
      #    php artisan key:generate
      # Install testing dependencies
      - name: Install Testing Dependencies
        run: | 
          sudo apt-get update -qq -y
          sudo apt-get install -qq -y bash shellcheck
      # Shellcheck Tests
      - name: Run Shellcheck Testing
        run: shellcheck -s bash -x ./bin/easydock
      # Simple unit testing
      - name: Run Unit Testing
        run: |
          cd test-app
          bash ../bin/easydock init
          if [ -f .env.easydock ]; then
            echo "Init EasyDock success"
            bash ../bin/easydock build
            bash ../bin/easydock up
          else
            echo "Init EasyDock fail"
            exit 1
          fi
        env:
          TERM: xterm-256color